const VOCAB_DATA = [
  
  { char: '上课', py: 'shàng kè', ms: 'masuk kelas / menghadiri kelas', en: 'attend class', topic: 'Topic 2', emoji: '🏫', strokes: [['上'], ['讠','课']], tip: '上 = 3 strokes. 课 = 10 strokes (speech radical 讠).', count: '3 + 10 = 13' },
  { char: '儿歌', py: 'ér gē', ms: 'lagu kanak-kanak', en: "children's song", topic: 'Topic 2', emoji: '🎵', strokes: [['儿'], ['欠','歌']], tip: '儿 = 2 strokes. 歌 = 14 strokes (yawn radical 欠 on the right).', count: '2 + 14 = 16' },
  { char: '故事', py: 'gù shi', ms: 'cerita', en: 'story', topic: 'Topic 2', emoji: '📖', strokes: [['攵','故'], ['事']], tip: '故 = 9 strokes. 事 = 8 strokes.', count: '9 + 8 = 17' },
  { char: '知识', py: 'zhī shi', ms: 'pengetahuan / ilmu', en: 'knowledge', topic: 'Topic 2', emoji: '🧠', strokes: [['矢','知'], ['讠','识']], tip: '知 = 8 strokes. 识 = 7 strokes (speech radical 讠).', count: '8 + 7 = 15' },
  { char: '爸爸', py: 'bà ba', ms: 'ayah / bapa', en: 'father', topic: 'Topic 3', emoji: '👨', strokes: [['父','爸'], ['爸爸']], tip: '爸 = 8 strokes: father radical 父 on top, 巴 below.', count: '8 + 8 = 16' },
  { char: '回来', py: 'huí lái', ms: 'balik / kembali', en: 'come back / return', topic: 'Topic 3', emoji: '🔙', strokes: [['囗','回'], ['木','来']], tip: '回 = 6 strokes: two nested squares. 来 = 7 strokes.', count: '6 + 7 = 13' },
  { char: '姐姐', py: 'jiě jie', ms: 'kakak perempuan', en: 'older sister', topic: 'Topic 3', emoji: '👧', strokes: [['女','姐'], ['姐姐']], tip: '姐 = 8 strokes: woman radical 女 on left.', count: '8 + 8 = 16' },
  { char: '笑声', py: 'xiào shēng', ms: 'bunyi ketawa', en: 'laughter', topic: 'Topic 3', emoji: '😂', strokes: [['⺮','笑'], ['士','声']], tip: '笑 = 10 strokes: bamboo radical on top.', count: '10 + 7 = 17' },
  { char: '星星', py: 'xīng xing', ms: 'bintang', en: 'stars', topic: 'Topic 3', emoji: '⭐', strokes: [['日','星'], ['星星']], tip: '星 = 9 strokes: sun radical 日 on top.', count: '9 + 9 = 18' },
  { char: '吃饭', py: 'chī fàn', ms: 'makan', en: 'to eat a meal', topic: 'Topic 4', emoji: '🍚', strokes: [['口','吃'], ['饣','饭']], tip: '吃 = 6 strokes. 饭 = 7 strokes.', count: '6 + 7 = 13' },
  { char: '饭菜', py: 'fàn cài', ms: 'lauk-pauk', en: 'food and dishes', topic: 'Topic 4', emoji: '🍱', strokes: [['饣','饭'], ['艹','菜']], tip: '饭 = 7 strokes. 菜 = 11 strokes.', count: '7 + 11 = 18' },
  { char: '瓜', py: 'guā', ms: 'tembikai', en: 'melon', topic: 'Topic 4', emoji: '🍉', strokes: [['瓜']], tip: '瓜 = 5 strokes.', count: '5' },
  { char: '喜欢', py: 'xǐ huān', ms: 'suka', en: 'to like', topic: 'Topic 4', emoji: '❤️', strokes: [['壴','喜'], ['欠','欢']], tip: '喜 = 12 strokes. 欢 = 6 strokes.', count: '12 + 6 = 18' },
  { char: '妹妹', py: 'mèi mei', ms: 'adik perempuan', en: 'younger sister', topic: 'Topic 4', emoji: '👧🏻', strokes: [['女','妹'], ['妹妹']], tip: '妹 = 8 strokes.', count: '8 + 8 = 16' },
  { char: '积木', py: 'jī mù', ms: 'blok mainan', en: 'building blocks', topic: 'Topic 4', emoji: '🧱', strokes: [['禾','积'], ['木']], tip: '积 = 10 strokes.', count: '10 + 4 = 14' },
  { char: '房子', py: 'fáng zi', ms: 'rumah', en: 'house', topic: 'Topic 4', emoji: '🏠', strokes: [['宀','房'], ['子']], tip: '房 = 8 strokes. 子 = 3 strokes.', count: '8 + 3 = 11' },
  { char: '我', py: 'wǒ', ms: 'saya', en: 'I / me', topic: 'Topic 4', emoji: '🧒', strokes: [['我']], tip: '我 = 7 strokes.', count: '7' },
  { char: '游乐场', py: 'yóu lè chǎng', ms: 'taman permainan', en: 'playground', topic: 'Topic 4', emoji: '🛝', strokes: [['氵','游'], ['乐'], ['土','场']], tip: '游 = 12 strokes. 乐 = 5 strokes. 场 = 6 strokes.', count: '12 + 5 + 6 = 23' },
  { char: '露珠', py: 'lù zhū', ms: 'titisan embun', en: 'dewdrop', topic: 'Topic 5', emoji: '💧', strokes: [['雨','露'], ['王','珠']], tip: '露 = 21 strokes (rain radical 雨). 珠 = 10 strokes.', count: '21 + 10 = 31' },
  { char: '照相', py: 'zhào xiàng', ms: 'tangkap gambar', en: 'take a photo', topic: 'Topic 5', emoji: '📷', strokes: [['灬','照'], ['木','相']], tip: '照 = 13 strokes (fire radical 灬). 相 = 9 strokes.', count: '13 + 9 = 22' },
  { char: '月亮', py: 'yuè liang', ms: 'bulan', en: 'moon', topic: 'Topic 5', emoji: '🌙', strokes: [['月'], ['亠','亮']], tip: '月 = 4 strokes. 亮 = 9 strokes.', count: '4 + 9 = 13' },
  { char: '红花', py: 'hóng huā', ms: 'bunga merah', en: 'red flower', topic: 'Topic 5', emoji: '🌺', strokes: [['纟','红'], ['艹','花']], tip: '红 = 6 strokes (silk radical 纟). 花 = 7 strokes (grass radical 艹).', count: '6 + 7 = 13' },
  { char: '雨停了', py: 'yǔ tíng le', ms: 'hujan berhenti', en: 'rain stopped', topic: 'Topic 5', emoji: '🌦️', strokes: [['雨'], ['亻','停'], ['了']], tip: '雨 = 8 strokes. 停 = 11 strokes. 了 = 2 strokes.', count: '8 + 11 + 2 = 21' },
  { char: '青山', py: 'qīng shān', ms: 'gunung hijau', en: 'green mountain', topic: 'Topic 5', emoji: '⛰️', strokes: [['青'], ['山']], tip: '青 = 8 strokes. 山 = 3 strokes.', count: '8 + 3 = 11' },
  { char: '弯曲', py: 'wān qū', ms: 'bengkang-bengkok', en: 'curved / winding', topic: 'Topic 5', emoji: '〰️', strokes: [['弓','弯'], ['曲']], tip: '弯 = 9 strokes. 曲 = 6 strokes.', count: '9 + 6 = 15' },
  { char: '小河', py: 'xiǎo hé', ms: 'sungai kecil', en: 'small river', topic: 'Topic 5', emoji: '🏞️', strokes: [['小'], ['氵','河']], tip: '小 = 3 strokes. 河 = 8 strokes (water radical 氵).', count: '3 + 8 = 11' },
  { char: '只', py: 'zhī', ms: 'penjodoh bilangan (ekor)', en: 'measure word (animals)', topic: 'Topic 5', emoji: '🔢', strokes: [['口','只']], tip: '只 = 5 strokes. Used as a measure word for animals like birds or cats.', count: '5' },
// ── Topic 6 ───────────────────────────────────────────────
  { char: '老虎', py: 'lǎo hǔ', ms: 'harimau', en: 'tiger', topic: 'Topic 6', emoji: '🐯', strokes: [['老'], ['虎']], tip: '虎 = 8 strokes. The top part represents the tiger\'s head.', count: '6 + 8 = 14' },
  { char: '小猫', py: 'xiǎo māo', ms: 'anak kucing', en: 'kitten', topic: 'Topic 6', emoji: '🐱', strokes: [['小'], ['犭','猫']], tip: '猫 has the animal radical 犭 on the left.', count: '3 + 11 = 14' },
  { char: '多少', py: 'duō shǎo', ms: 'berapa banyak', en: 'how many', topic: 'Topic 6', emoji: '❓', strokes: [['夕','多'], ['少']], tip: '多 is two "evening" 夕 characters stacked.', count: '6 + 4 = 10' },
  { char: '一群', py: 'yì qún', ms: 'sekumpulan', en: 'a group / flock', topic: 'Topic 6', emoji: '🐑', strokes: [['一'], ['君','群']], tip: '群 has the sheep radical 羊 at the bottom right.', count: '1 + 13 = 14' },
  { char: '天鹅', py: 'tiān é', ms: 'angsa', en: 'swan', topic: 'Topic 6', emoji: '🦢', strokes: [['天'], ['我','鹅']], tip: '鹅 has the bird radical 鸟 on the right.', count: '4 + 13 = 17' },
  { char: '蚂蚁', py: 'mǎ yǐ', ms: 'semut', en: 'ant', topic: 'Topic 6', emoji: '🐜', strokes: [['虫','蚂'], ['虫','蚁']], tip: 'Both characters use the insect radical 虫.', count: '9 + 9 = 18' },
  { char: '小虫', py: 'xiǎo chóng', ms: 'ulat kecil', en: 'small bug', topic: 'Topic 6', emoji: '🐛', strokes: [['小'], ['虫']], tip: '虫 is the basic character for insects/bugs.', count: '3 + 6 = 9' },
  { char: '搬不动', py: 'bān bú dòng', ms: 'tidak boleh angkat', en: 'cannot move', topic: 'Topic 6', emoji: '📦', strokes: [['扌','搬'], ['不'], ['力','动']], tip: '搬 uses the hand radical 扌 because moving requires hands.', count: '13 + 4 + 6 = 23' },
  { char: '重', py: 'zhòng', ms: 'berat', en: 'heavy', topic: 'Topic 6', emoji: '🏋️', strokes: [['重']], tip: '重 = 9 strokes. Think of a heavy load on a person.', count: '9' },


   
  // ─── TOPIC 8 ──────────────────────────────────────────
 { char: '香蕉', py: 'xiāng jiāo', ms: 'pisang', en: 'banana', topic: 'Topic 8.1', emoji: '🍌', strokes: [['禾','香'], ['艹','蕉']], tip: '蕉 has the grass/plant radical 艹 on top, common for fruits and plants.', count: '9 + 15 = 24' },
  { char: '黄色', py: 'huáng sè', ms: 'warna kuning', en: 'yellow color', topic: 'Topic 8.1', emoji: '💛', strokes: [['黄'], ['色']], tip: '黄 means yellow. 色 means color.', count: '11 + 6 = 17' },
  { char: '滑梯', py: 'huá tī', ms: 'papan gelongsor', en: 'slide', topic: 'Topic 8.1', emoji: '🛝', strokes: [['氵','滑'], ['木','梯']], tip: '滑 has the water radical 氵 (slippery/smooth). 梯 has the wood radical 木 (ladders were made of wood).', count: '12 + 11 = 23' },
  { char: '爬山', py: 'pá shān', ms: 'mendaki gunung', en: 'climb a mountain', topic: 'Topic 8.1', emoji: '🧗', strokes: [['爪','爬'], ['山']], tip: '爬 has the claw radical 爪, like grabbing things to climb. 山 looks like three mountain peaks.', count: '8 + 3 = 11' },
  { char: '快乐', py: 'kuài lè', ms: 'gembira', en: 'happy', topic: 'Topic 8.1', emoji: '😊', strokes: [['忄','快'], ['乐']], tip: '快 has the standing heart radical 忄, which is used for feelings and emotions.', count: '7 + 5 = 12' },
  { char: '唱歌', py: 'chàng gē', ms: 'menyanyi', en: 'sing a song', topic: 'Topic 8.2', emoji: '🎤', strokes: [['口','唱'], ['欠','歌']], tip: 'Both characters are related to the mouth/breath! 唱 has the mouth radical 口 on the left.', count: '11 + 14 = 25' },
  { char: '响起', py: 'xiǎng qǐ', ms: 'berbunyi / bergema', en: 'sound / ring', topic: 'Topic 8.2', emoji: '🔔', strokes: [['口','响'], ['走','起']], tip: '响 (sound) has the mouth radical 口. 起 (rise/start) has the walk radical 走.', count: '9 + 10 = 19' },
  { char: '落下', py: 'luò xià', ms: 'jatuh', en: 'fall down / drop', topic: 'Topic 8.2', emoji: '🍂', strokes: [['艹','落'], ['下']], tip: '落 has the plant radical 艹, like falling autumn leaves. 下 is an arrow pointing down.', count: '12 + 3 = 15' },
  { char: '风儿', py: 'fēng ér', ms: 'angin', en: 'wind', topic: 'Topic 8.2', emoji: '🌬️', strokes: [['风'], ['儿']], tip: '风 is the radical for wind. 儿 makes the word sound softer and more poetic.', count: '4 + 2 = 6' },
  { char: '在', py: 'zài', ms: 'di / sedang', en: 'at / in / on', topic: 'Topic 8.2', emoji: '📍', strokes: [['土','在']], tip: '在 has the earth/ground radical 土 inside it. Used to show location or ongoing action.', count: '6' }
  
];
